// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysUser = "sys_user"

// SysUser 用户表
type SysUser struct {
	ID       int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Username string `gorm:"column:username;type:varchar(50);not null;comment:用户名" json:"username"` // 用户名
	Password string `gorm:"column:password;type:varchar(100);not null;comment:密码" json:"password"` // 密码
	Nickname string `gorm:"column:nickname;type:varchar(100);comment:昵称" json:"nickname"`          // 昵称
	DepID    int64  `gorm:"column:dep_id;type:int" json:"dep_id"`
	PosID    string `gorm:"column:pos_id;type:varchar(255)" json:"pos_id"`
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
