// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameScreenDatum = "screen_datum"

// ScreenDatum 大屏数据
type ScreenDatum struct {
	ID        int64      `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	ProjectID int64      `gorm:"column:project_id;type:int;comment:project ID" json:"project_id"`       // project ID
	UserID    int64      `gorm:"column:user_id;type:int;comment:用户 ID" json:"user_id"`                  // 用户 ID
	Content   string     `gorm:"column:content;type:text;comment:内容数据" json:"content"`                  // 内容数据
	CreateAt  *time.Time `gorm:"column:create_at;type:int unsigned;autoCreateTime" json:"create_at"`    // 创建时间
}

// TableName ScreenDatum's table name
func (*ScreenDatum) TableName() string {
	return TableNameScreenDatum
}
